# config/meta.yml

meta_product_name: "HOPdesk"
meta_title: "HOPdesk - Find somewhere to work in your local area"
meta_description: "Find somewhere to work in your local area"
meta_image: "cover.png" # should exist in `app/assets/images/`

