# config/meta.yml

meta_product_name: "Hopdesk"
meta_title: "Hopdesk - Find somewhere to work in your local area"
meta_description: "Relevant description"
meta_image: "cover.png" # should exist in `app/assets/images/`

